export const MOCK_REPOS = [
  { id: 'repo-1', owner: 'vercel', name: 'next.js', full_name: 'vercel/next.js', description: 'The React Framework for the Web', language: 'TypeScript', stars: 128000 },
  { id: 'repo-2', owner: 'tailwindlabs', name: 'tailwindcss', full_name: 'tailwindlabs/tailwindcss', description: 'A utility-first CSS framework', language: 'CSS', stars: 82000 },
  { id: 'repo-3', owner: 'supabase', name: 'supabase', full_name: 'supabase/supabase', description: 'The open source Firebase alternative', language: 'TypeScript', stars: 74000 },
  { id: 'repo-4', owner: 'prisma', name: 'prisma', full_name: 'prisma/prisma', description: 'Next-generation ORM for Node.js & TypeScript', language: 'TypeScript', stars: 38000 },
  { id: 'repo-5', owner: 'vitejs', name: 'vite', full_name: 'vitejs/vite', description: 'Next generation frontend tooling', language: 'TypeScript', stars: 68000 },
  { id: 'repo-6', owner: 'openai', name: 'openai-python', full_name: 'openai/openai-python', description: 'Official Python client library for the OpenAI API', language: 'Python', stars: 24000 },
]

export const MOCK_ARTICLES = [
  {
    id: 'article-1',
    repo_id: 'repo-1',
    title: 'Next.js just deprecated the old way of building pages — new projects will work differently',
    one_liner: 'Next.js deprecated its old routing system — if you have an existing project, it still works for now, but new AI-generated Next.js code will look totally different',
    severity: 5,
    categories: ['BREAKING', 'DEPRECATION'],
    published_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    is_quarantined: false,
    what_changed: 'Next.js switched to a new way of organizing your app\'s pages. The old approach (putting files in a "pages" folder) still works but is now officially on its way out — you\'ll see a warning when you start your app. Any new Next.js project you create, or any code an AI writes for you today, will use the new "app" folder structure instead. This matters because the old and new styles are quite different, so mixing them can get confusing fast.',
    what_to_do: 'If you\'re starting a fresh project, don\'t worry — just go with whatever the setup wizard gives you and you\'ll be on the new system. If you have an existing project that still uses the "pages" folder, it\'s safe to keep using it for now, but plan to migrate eventually. When you ask an AI to add new pages, tell it which style your project uses so it doesn\'t mix them up.',
    citations: [
      { claim: 'pages/ router is deprecated', source_excerpt: 'The Pages Router is now deprecated and will be removed in a future major release.', url: 'https://nextjs.org/docs' },
    ],
    repos: { owner: 'vercel', name: 'next.js' },
  },
  {
    id: 'article-2',
    repo_id: 'repo-2',
    title: 'Tailwind CSS just changed how you configure it — the config file is gone',
    one_liner: 'Tailwind v4 scrapped the JavaScript config file entirely — if you upgrade, your custom colors and settings will break until you move them',
    severity: 4,
    categories: ['BREAKING', 'FEATURE'],
    published_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    is_quarantined: false,
    what_changed: 'Tailwind v4 got rid of the `tailwind.config.js` file — all your customizations (colors, fonts, spacing) now live inside your CSS file instead. This is a big structural change: if you upgrade and had custom settings in that config file, they\'ll simply stop working until you move them. The upside is that building your CSS is now dramatically faster.',
    what_to_do: 'Don\'t upgrade to v4 without a plan. Run their automatic migration tool first (`npx @tailwindcss/upgrade`) — it handles most of the conversion for you. If you\'re starting a new project, v4 is the way to go. If you have a working project on v3, it\'s safe to stay there until you have time to migrate properly.',
    citations: [
      { claim: 'tailwind.config.js no longer supported', source_excerpt: 'Configuration is now done entirely in CSS using the @theme directive.' },
    ],
    repos: { owner: 'tailwindlabs', name: 'tailwindcss' },
  },
  {
    id: 'article-3',
    repo_id: 'repo-3',
    title: 'Supabase auth bug is causing apps to freeze — downgrade immediately if affected',
    one_liner: 'A bug in a recent Supabase package update is making apps get stuck in an endless login loop — downgrade now if you updated in the last week',
    severity: 5,
    categories: ['SECURITY', 'BUGFIX'],
    published_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    is_quarantined: false,
    what_changed: 'A bug snuck into `@supabase/ssr` versions 0.5.0 through 0.5.2 that causes apps to freeze or crash when a user\'s session expires. Instead of logging the user out gracefully, the app gets stuck bouncing them back and forth in an endless loop. It happens silently on the default settings, so your users might be hitting it without you knowing.',
    what_to_do: 'Check your package.json — if you\'re on `@supabase/ssr` version 0.5.0, 0.5.1, or 0.5.2, downgrade to 0.4.0 right now (`npm install @supabase/ssr@0.4.0`). A fix is coming within 48 hours, but don\'t wait for it if you have active users. This one is worth acting on today.',
    citations: [
      { claim: 'Infinite redirect loop confirmed', source_excerpt: 'Confirmed reproduction: expired refresh token + autoRefreshToken: true → 302 loop.', url: 'https://github.com/supabase/ssr' },
    ],
    repos: { owner: 'supabase', name: 'supabase' },
  },
  {
    id: 'article-4',
    repo_id: 'repo-4',
    title: 'Prisma 6 dropped support for older Node.js and changed how MongoDB works',
    one_liner: 'Prisma 6 requires a newer version of Node.js, and MongoDB users need to install an extra package — easy fixes, but you need to know about them before upgrading',
    severity: 4,
    categories: ['BREAKING', 'DEPRECATION'],
    published_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    is_quarantined: false,
    what_changed: 'Prisma 6 no longer works with Node.js 16 — you\'ll need Node 18 or newer. If you use MongoDB with Prisma, it\'s also been moved to a separate package you\'ll need to install yourself. Neither of these is a huge deal, but if you just run `npm update prisma` without checking, things will break.',
    what_to_do: 'Before upgrading, check your Node.js version (`node -v`) — if it shows v16.x, upgrade Node first. If you use MongoDB, install the new connector package (`npm install @prisma/mongodb`) and update your database config. If you\'re on PostgreSQL or another database, it\'s a straightforward upgrade.',
    citations: [],
    repos: { owner: 'prisma', name: 'prisma' },
  },
  {
    id: 'article-5',
    repo_id: 'repo-5',
    title: 'Vite 6 just made your builds significantly faster with almost no changes needed',
    one_liner: 'Vite 6 switched to a faster build engine under the hood — your builds will be 3–8× faster and most projects need zero changes to upgrade',
    severity: 3,
    categories: ['FEATURE', 'PERF'],
    published_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    is_quarantined: false,
    what_changed: 'Vite 6 swapped its internal build engine for a faster Rust-based one called Rolldown. You won\'t notice any difference in how you use Vite — your config, your commands, everything stays the same — but production builds are now 3 to 8 times faster. Most projects can upgrade with no changes at all.',
    what_to_do: 'This is a good upgrade to make. Run `npm update vite` and test your production build. If something breaks (rare, but possible if you use advanced build plugins), check the Vite 6 release notes for the short list of edge cases. Otherwise, enjoy the speed boost.',
    citations: [],
    repos: { owner: 'vitejs', name: 'vite' },
  },
  {
    id: 'article-6',
    repo_id: 'repo-6',
    title: 'The OpenAI Python SDK removed the simple, synchronous way of calling the API',
    one_liner: 'OpenAI\'s Python library v2 dropped the straightforward call style — any code that makes API calls the old way will crash on upgrade',
    severity: 4,
    categories: ['BREAKING'],
    published_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    is_quarantined: false,
    what_changed: 'The OpenAI Python library dropped the simple, blocking style of making API calls. Previously you could just call the API and wait for the result; now every call needs to be written in Python\'s async style. If an AI wrote your OpenAI integration, there\'s a good chance it used the old style — that code will break when you upgrade the package.',
    what_to_do: 'Don\'t upgrade to v2 until you\'re ready to update your code. When you do upgrade, ask your AI to rewrite the OpenAI calls in async style — it\'s a mechanical change and any coding AI handles it well. If you\'re starting fresh, just tell your AI you\'re using openai-python v2 and it\'ll write the right style from the start.',
    citations: [],
    repos: { owner: 'openai', name: 'openai-python' },
  },
]

export const MOCK_UPDATES = [
  {
    id: 'update-1',
    repo_id: 'repo-1',
    one_liner: 'Improved HMR speed for large monorepos — cold start reduced by ~40%',
    severity: 2,
    categories: ['PERF'],
    published_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    repos: { owner: 'vercel', name: 'next.js' },
  },
  {
    id: 'update-2',
    repo_id: 'repo-3',
    one_liner: 'Supabase Storage now supports resumable uploads up to 50GB',
    severity: 2,
    categories: ['FEATURE'],
    published_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    repos: { owner: 'supabase', name: 'supabase' },
  },
  {
    id: 'update-3',
    repo_id: 'repo-5',
    one_liner: 'Vite 6.1 — `@vitejs/plugin-react` now supports React compiler by default',
    severity: 2,
    categories: ['FEATURE'],
    published_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    repos: { owner: 'vitejs', name: 'vite' },
  },
]
